name: Main Pipeline

on:
  workflow_dispatch:

jobs:
  build_test:
    uses: ./.github/workflows/blank.yml

  deploy:
    needs: build_test
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: production
